[project]
name = "turbines"
version = "0.1.7"
description = "A simple static site generator with live reload"
readme = "README.md"
authors = [{ name = "nfast", email = "turbines@nilsfast.com" }]
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "jinja2-simple-tags>=0.6.1",
    "markdown>=3.10",
    "pydantic>=2.12.5",
    "pyyaml>=6.0.3",
    "tornado>=6.5.3",
    "typer>=0.20.0",
    "watchfiles>=1.1.1",
    "websockets>=15.0.1",
]

[project.scripts]
turbines = "turbines.cli:app"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "python-semantic-release>=10.5.3",
    "types-colorama>=0.4.15.20250801",
    "types-markdown>=3.10.2.20260211",
    "types-pycurl>=7.45.7.20251101",
    "types-pygments>=2.19.0.20251121",
    "types-pyyaml>=6.0.12.20250915",
]
